# Generated by Django 2.2 on 2019-05-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaterial',
            name='material',
            field=models.ManyToManyField(blank=True, through='myapp.MaterialItem', to='myapp.Material'),
        ),
    ]
