# Generated by Django 2.2 on 2019-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='materialitem',
            field=models.ManyToManyField(to='myapp.MaterialItem'),
        ),
    ]
