# Generated by Django 2.2 on 2019-05-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymaterialprocess',
            name='materialitem',
        ),
    ]
