# Generated by Django 2.2 on 2019-05-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190522_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Material'),
        ),
    ]
