# Generated by Django 2.2 on 2019-05-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stock_materialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaterial',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Stock'),
        ),
    ]
