# Generated by Django 2.2 on 2019-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_materialitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialitem',
            name='material',
        ),
        migrations.AddField(
            model_name='materialitem',
            name='material',
            field=models.ManyToManyField(to='myapp.Material'),
        ),
    ]
