# Generated by Django 2.2 on 2019-05-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_buymaterialprocess_materialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymaterialprocess',
            name='materialitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.MaterialItem'),
        ),
    ]
