# Generated by Django 2.2 on 2019-05-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190430_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialitem',
            name='material',
        ),
        migrations.AddField(
            model_name='materialitem',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Material'),
        ),
    ]
