# Generated by Django 2.2 on 2019-05-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ordermaterial_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='materialitem',
        ),
    ]
