# Generated by Django 2.2 on 2019-05-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190522_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialitem',
            name='orderMaterial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.OrderMaterial'),
        ),
    ]
