# Generated by Django 2.2 on 2019-05-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buymaterialprocess_materialitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaterial',
            name='materialitem',
        ),
        migrations.AddField(
            model_name='materialitem',
            name='orderMaterial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.OrderMaterial'),
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='materialitems',
            field=models.ManyToManyField(through='myapp.MaterialItem', to='myapp.Material'),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='menuitem',
            field=models.ManyToManyField(to='myapp.MenuItem'),
        ),
    ]
