# Generated by Django 2.2 on 2019-05-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_stock_materialitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaterial',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='materialitem',
            field=models.ManyToManyField(to='myapp.MaterialItem'),
        ),
    ]
