# Generated by Django 2.2 on 2019-05-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190522_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymaterialprocess',
            name='orderMaterial',
        ),
        migrations.RemoveField(
            model_name='materialitem',
            name='orderMaterial',
        ),
        migrations.AddField(
            model_name='buymaterialprocess',
            name='materialItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.MaterialItem'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='OrderMaterial',
        ),
    ]
