# Generated by Django 2.2 on 2019-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190525_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymaterialprocess',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
