# Generated by Django 2.2 on 2019-05-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190524_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialitem',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
