# Generated by Django 2.2 on 2019-05-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190522_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymaterialprocess',
            name='materialItem',
        ),
        migrations.AddField(
            model_name='buymaterialprocess',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Material'),
        ),
    ]
