# Generated by Django 2.2 on 2019-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190507_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialitem',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
