# Generated by Django 2.2 on 2019-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190524_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialitem',
            name='orderMaterial',
        ),
        migrations.RemoveField(
            model_name='ordermaterial',
            name='materialitems',
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='materialitem',
            field=models.ManyToManyField(blank=True, to='myapp.MaterialItem'),
        ),
    ]
