# Generated by Django 2.2 on 2019-05-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_buymaterialprocess_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='materialitem',
        ),
        migrations.AddField(
            model_name='materialitem',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Stock'),
        ),
    ]
