# Generated by Django 2.2 on 2019-05-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190526_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialitem',
            name='stock',
        ),
    ]
