# Generated by Django 2.2 on 2019-05-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190525_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymaterialprocess',
            name='materialitem',
        ),
    ]
