# Generated by Django 2.2 on 2019-05-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_materialitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Material'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
    ]
