# Generated by Django 2.2 on 2019-05-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_buymaterialprocess_materialitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymaterialprocess',
            name='materialitem',
        ),
        migrations.RemoveField(
            model_name='ordermaterial',
            name='materialitem',
        ),
        migrations.AddField(
            model_name='materialitem',
            name='orderMaterial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.OrderMaterial'),
        ),
    ]
