# Generated by Django 2.2 on 2019-05-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190526_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Restaurant'),
        ),
    ]
