# Generated by Django 2.2 on 2019-05-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190526_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Material'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
