# Generated by Django 2.2 on 2019-05-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190526_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Material')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Stock')),
            ],
        ),
    ]
